### ISSUE TITLE
Feature request: fragments only hidden when visiting the slide the first time

### ISSUE THREAD

**Issue by kiryph** [hakimel/reveal.js#1071]
I've been using [latex-beamer](http://en.wikipedia.org/wiki/Beamer_%28LaTeX%29) for my talks. One thing I particularly miss is a possibility to save the state of a slide when unrevealing `fragments`. Either because of questions I want to go backwards to past slides without going through all `fragments` again or I notice that I want to show already the next slide without showing everything of the current slide.

I know there is the overview feature. But often you just want to jump one slide back without distracting the audience by opening an overview of the talk.

I see a great possibility in the approach of `vertical slides` of `reveal.js` to handle this elegantly.
Going downwards could mean unrevealing `fragments` and sidewards to next or previous slide as it has been left (i.e. first or last visited vertical slide of this 'slide group').

Is it possible to use reveal.js in such a way? Your documentation https://github.com/hakimel/reveal.js#fragments says
> Every element with the class fragment will be stepped through before moving on to the next slide.

So I assume currently it is not possible.

**Comment by bchretien** [comment]
:+1:

**Comment by slipring** [comment]
for your own customizerly purposes, I'd recall:


Reveal.configure({ fragments: false });

Reveal.sync();


I think some triggering of this could do this job..

I have used a 'checkbox hack' (hidden toggleboxing) at some point to
turn fragments on and off for the whole show without needing to
reinitialize the whole splay. So I imagine one might be able to
incerpt

fragments: false + sync to the right nav arrow, fragments: true + sync
calls to the down one. Before the slide change? Or even after, if you
want to start with a little bit then a big reveal of all defragged
once.

drft

**Comment by kiryph** [comment]
I am not yet familiar with reveal.js to fully understand what fragments:false and syncs mean.

However, if I don't use fragments for the overlays but vertical slides to unhide elements.
I could remap the keys of the Presenter as following:
Presenter <right> means <Next Slide> and Presenter <left> means <Navigate Left>.

I would get the desired behaviour for already shown slides, which would be an improvement.

Is this correct?

**Comment by demoneaux** [comment]
I don't think this is possible currently, and would require a lot of major code changes. @hakimel do you think this change is necessary?

**Comment by hakimel** [comment]
Hey. If I've understood comments correctly you want to ignore stepping through fragments when navigating through your horizontal slides, and only reveal fragments when pressing up/down? This isn't how I think the framework should behave but you could manually tweak it to work like that. Try replacing the following two lines in your reveal.js file:

https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L3746 -> `if( availableRoutes().left ) {`
https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L3761 -> `if( availableRoutes().right ) {`

**Comment by Hotschke** [comment]
@hakimel yes and no. Yes, this would give the speaker a method to resolve the issue of clicking desperately many times to go to already shown slides. Thanks for your code change suggestion.

And no: Most presenter tools (I mean the hardware devices often combined with a laser pointer) have often only left and right buttons because they are not aware of vertical slides which I consider quite an uncommon feature. I guess these devices send keycodes corresponding to the left and right arrow keys. For instance, MS Powerpoint, PDFs and other established tools for talks do not have vertical slides.

Also I think to remove any additional burden of a stressed speaker it would be great if the speaker could stick to only next and previous slide actions and do not have to use also down to proceed the talk.

So IMHO, reveal.js should remember whether a slide has already been visited. Browser cache or a cookie would offer means to do this. If the speaker actually want to hide fragments again, additional keys are actually necessary. This could be up/down keys. So for this case up and down keys on the laptop have to be used if not available on the presenter device. However, this is the more uncommon case. I myself have not yet seen any talk where someone wanted to unhide already shown lines, but speaker always go back to older slides in almost every talk.

Since no one else is interested in this the wontfix label seems to be appropriate.

**Comment by Hotschke** [comment]
I just want to mention that there is the presentation framework https://github.com/shower/shower which exactly works like this issue is asking about. See demo presentation slide 11 (http://shwr.me/#11).

**Comment by kiryph** [comment]
Another presentation tool is https://github.com/pdfpc/pdfpc which added my feature request https://github.com/pdfpc/pdfpc/issues/242.

It is realized by a new method of going forwards/backwards:

> j/k Go to the previous / next slide, skipping over overlays that have already been viewed, but at most one user slide.

I admit they swapped the meaning of the vi-like inspired key bindings.
But a user can map the arrow keys to use it exclusively during the presentation which is actually what I want.

Unfortunately, macOS support of pdfpc is limited. Also I recently discovered that I can have interactive Mayavi renderings in Jupyter Notebooks which again can be shown as a Live Reveal.js presentations with the help of RISE (https://damianavila.github.io/RISE/index.html).

I still would like to see this behavior added to reveal.js.

When I look back at my original post, I think I should have written this issue with a more general question which could have inspired a wider discussion with different solution approaches.
