### ISSUE TITLE
State of this repo?!

### ISSUE THREAD

**Issue by lfilho** [hakimel/reveal.js#1142]
Hello @hakimel thanks for this great project!!

Have you dropped support for reveal.js? There's seems to be many opened PR's and Issues and no ones to take care of them.

Thanks

**Comment by hakimel** [comment]
You're welcome. No, I'm still supporting it. 3.0 was released just over a month ago and I've put in quite a few commits since then if you check out the logs.

It's just been impossible for me to keep up with the quantity of issues and pull requests lately. I'm hopeful to catch up more whenever I can find time but there's many days worth of issues and PRs to review.

**Comment by lfilho** [comment]
How good to hear from you! Cool.

Maybe you'll find useful to elect a small team of core committers to help you out in this quest :)
Because, actually, there's many **years** worth of issues and PRs. :sweat_smile: 

Thanks again
