### ISSUE TITLE
How to terminate / destroy reveal.js -- feature request?

### ISSUE THREAD

**Issue by mela-s** [hakimel/reveal.js#1145]
Is there a way to terminate/destroy reveal.js? I tried using `Reveal.removeEventListeners()` which I found on another thread, but it doesn't do what I want... I'm looking for a way to toggle reveal.js and allow the user to view it the site as a "regular" scrolling website.

Thanks.

**Comment by hakimel** [comment]
There isn't, reveal.js makes lots of changes to the DOM so it would be difficult to roll all that back. Perhaps you could work around this by reloading the page and not initializing the framework.

**Comment by Kadbury1989** [comment]
When loading Reveal video presentation in a bootstrap popup, closing the popup and re-opening the popup will mess with the video playback. When the video slide previously playing is getting played again, 2 video will start playing. Both videos are the same slide, one from DOM and one from current slide I guess. Page reload is not an option here. Also removing these previous slides do not seem to work.

**Comment by Mister-Hope** [comment]
> There isn't, reveal.js makes lots of changes to the DOM so it would be difficult to roll all that back. Perhaps you could work around this by reloading the page and not initializing the framework.

I bet you noticed that there are many people complaining about the hash changes when scrolling down and up when already leaving a page with reveal js.

I still **VERY CONFUSED** why are you guys adding a scroll event listener to root, but just leave it as is when calling `reveal.removeEventListeners()`. So scroll event listener IS NOT a event listener right? 👎👎👎👎👎👎👎

I fully understand that it's hard to roll back, and I understand that this feature can not be provided. And I can clean up the mess DOM myself.🙂

But without the actual lister function inside the reveal.js, it's IMPOSSIABLE for us to unregister any event listener. So at leat, PLEASE provide a way to remove all event listerners. Otherwise dumplicated listeners will be added when initialize reveal.js mutiple  times, and that can be called **"A memory leak"**. PLZ fix that.

**Comment by flaming-cl** [comment]
> This feature has been added. You can now call `Reveal.destroy()` to uninitialize reveal.js which will remove all event listeners, roll back changes to the DOM and unlink all registered plugins.

Great! Are you going to release this feature in the latest npm package?

**Comment by hakimel** [comment]
The new `destroy` method is available in reveal.js 4.3.0 which was released today 🚀

**Comment by Mister-Hope** [comment]
Thanks for that.

**Comment by Mister-Hope** [comment]
I am not sure, but I am not seeing a commit that updates docs, maybe we should add it in the docs? @hakimel

**Comment by hakimel** [comment]
It's already in the docs at the bottom here: https://revealjs.com/initialization/#destroy
