### ISSUE TITLE
Scrolling in overview mode on iPad not fluid

### ISSUE THREAD

**Issue by Pirouette04** [hakimel/reveal.js#1155]
Hi,

I'm thinking of use reveal.js in a projet, at this time I see just one stopper for this. The fluidity of the overview when I'm scrolling. 

Is the actual fluidity in overview mode is normal? 

Thanks!

**Comment by hakimel** [comment]
The overview isn't very smooth in its transitions on some devices. It's just a very heavy view to render since it shows so many slides at once, transformed down to a smaller size.

I haven't found a way to make it any faster but if it's unbearably slow I may revert back to not having any transition at all instead.
