### ISSUE TITLE
Problem when using "autoplay" parameter on embed link instead of "AutoPlay" feature

### ISSUE THREAD

**Issue by newyuppie** [hakimel/reveal.js#1214]
If I use "autoplay" parameter (on most video players you can attach ?autoplay=true at the end of embed URL), the videos start playing when loading the presentation, all at once. They should only autoplay upon entering the respective slide.

BTW, I'm forced to use the ?autoplay parameter because visual editor slides.com does not support AutoPlay feature for Wistia.

**Comment by hakimel** [comment]
This was addressed in Slides by lazy-loading all iframe elements only when their parent slide becomes visible. To lazy-load in reveal.js, swap out the "src" attribute on your iframe elements with "data-src".

**Comment by despairblue** [comment]
Shouldn't `data-src` load the iframe when they come into view distance? 

Reverting this *fix* would break the autoplay again, but it would make the `data-src- behaviour consistent and match the documentation in the README.md again.

So it would be better to use another attribute for not loading iframes before their slide is shown or update the documentation to reflect that `data-src` on an iframe behaves differently.

I have to use `src` and load all iframes upfront because otherwise it's inevitable that the slides containing iframes are shown without the iframe at first. It also makes slide animations laggy.

Great project btw!
