### ISSUE TITLE
SVG animation

### ISSUE THREAD

**Issue by hadim** [hakimel/reveal.js#1258]
I build a lot of SVG files with Inkscape to display figures inside reveal.js slides. I wonder to know if there is a way to animate these SVG ?

For example I would like to display a group in the SVG file first and then display another group by pressing "space" or "right arrow".

Thank you

**Comment by hadim** [comment]
Probably related to #1239

**Comment by flying-sheep** [comment]
check out [what i did](https://github.com/flying-sheep/revealjs-template/blob/master/src/data-src-svg.js) in my reveal-template project.

if you don’t want to use the whole thing (although i’m pretty fond of it), just use the code as plugin or inline (you’ll have to run it though e.g. babel first, though, since it’s ES6).

as the comment at the top explains, it accepts `<svg data-src="images/test.svg"></svg>`-style SVGs that will be embedded inline into the document.

if you use inkscape’s XML edior to add `class="fragment"` to `<g/>`s or other SVG elements, they will behave like expected when embedded that way.

**Comment by hadim** [comment]
That seems to fit exactly my needs !!!!

Unfortunately I am really bad with JS and I only want the code inside data-src-svg.js, but when I add it to index.html and call `loadDataSrcSVG();`, I have an error `Uncaught ReferenceError: loadDataSrcSVG is not defined(anonymous function) @ index.html:405`.

Could you help me with that ?

**Comment by hadim** [comment]
How it handles when there is multiple fragments in the same svg file ?

**Comment by flying-sheep** [comment]
about your second question: multiple fragments are handled fine :)

and about the first: it’s unfortunately a bit involved to get it to work without some other stuff.

1. you’ll need to run babel on it. [copy the code on the right][babel-code]
2. it needs a polyfill for *Promise*
3. it needs a polyfill for *fetch* (called “whatwg-fetch-polyfill” or so)

[babel-code]: https://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&playground=false&code=function%20loadDataSrcSVG%28%29%20{%0A%20%20let%20svgsToLoad%20%3D%20document.querySelectorAll%28%27svg[data-src]%27%29%0A%20%20%0A%20%20let%20loadSVGs%20%3D%20Array.map.call%28svgsToLoad%2C%20svg%20%3D%3E%20{%0A%20%20%20%20fetch%28svg.getAttribute%28%27data-src%27%29%29%0A%20%20%20%20%20%20.then%28response%20%3D%3E%20response.text%28%29%29%0A%20%20%20%20%20%20.then%28svgCode%20%3D%3E%20{%0A%20%20%20%20%20%20%20%20let%20svgDoc%20%3D%20new%20DOMParser%28%29.parseFromString%28svgCode%2C%20%27image%2Fsvg%2Bxml%27%29%0A%20%20%20%20%20%20%20%20let%20newSVG%20%3D%20svgDoc.documentElement%0A%20%20%20%20%20%20%20%20for%20%28let%20i%3D0%3B%20i%3Csvg.attributes.length%3B%20i%2B%2B%29%20{%0A%20%20%20%20%20%20%20%20%20%20let%20attr%20%3D%20svg.attributes[i]%0A%20%20%20%20%20%20%20%20%20%20newSVG.setAttribute%28attr.name%2C%20attr.value%29%0A%20%20%20%20%20%20%20%20}%0A%20%20%20%20%20%20%20%20svg.parentNode.replaceChild%28newSVG%2C%20svg%29%0A%20%20%20%20%20%20}%29%0A%20%20}%29%0A%20%20%0A%20%20Promise.all%28loadSVGs%29.then%28val%20%3D%3E%20{%0A%20%20%20%20let%20stretchSVGs%20%3D%20document.querySelectorAll%28%27svg.stretch%3Anot%28[preserveAspectRatio]%29%27%29%0A%09%09Array.map.call%28stretchSVGs%2C%20svg%20%3D%3E%20{%0A%09%09%09if%20%28!svg.hasAttribute%28%27viewBox%27%29%29%20{%0A%09%09%09%09let%20w%20%3D%20svg.getAttribute%28%27width%27%29%0A%09%09%09%09let%20h%20%3D%20svg.getAttribute%28%27height%27%29%0A%09%09%09%09svg.setAttribute%28%27viewBox%27%2C%20%600%200%20%24{w}%20%24{h}%60%29%0A%09%09%09}%0A%09%09%09svg.setAttribute%28%27preserveAspectRatio%27%2C%20%27xMidYMid%20meet%27%29%0A%09%09}%29%0A%09}%29%0A}

**Comment by hadim** [comment]
Thanks !

I don't really understand why you need to compile javascript to have another javascript code but whatever :-)

And last, what is a polyfill ? Is that a kind of JS plugin I need to include inside my presentation ?

**Comment by flying-sheep** [comment]
> I don't really understand why you need to compile javascript to have another javascript code but whatever :-)

haha, it’s new JS to older JS. you see those `let`s and `=>`? most browsers can’t handle them yet, so babel converts it.

> what is a polyfill ?

it’s simply a script that you include which makes new APIs available to for all browsers.

here’s [es6-promise](https://github.com/jakearchibald/es6-promise), which makes `new Promise` and `Promise.all(...)` and so on work, and here is [fetch](https://github.com/github/fetch), which makes `fetch(...)` work.

**Comment by hadim** [comment]
Thank you very much @flying-sheep. I finally decided to setup your whole system just to have svg fragment working :-) 

And it works really great !!!!!

**Comment by flying-sheep** [comment]
haha great, thanks! you get how it works?

you just run `gulp` and while it’s running you edit the `index.html`, `src/index.js` and `src/index.scss` files, and it will automatically refresh your browser once you save changes.

**Comment by ilpepe** [comment]
Hi,
sorry, but it seems i'm the noob here, and i don't really get how it works.

you'll have to load the js in the script in the html.

and then <svg data-src="images/test.svg"></svg> to insert the figure.

and then class=fragment needs to be added in the svg file. 

But i don't get how you can do a 'two step' animation. 
lets say layer 1 has to be there from the start. layer 2 come up after the first 'click', layer 3 goes over that with the next click, and layer 4 appears with yet another 'click' and layer 2 should then dissappear.
how do you define the order of the layers? is that the order of appearence in the xml?
is it possible to remove a layer again?

**Comment by flying-sheep** [comment]
that’s a bit more complicated, and has nothing to do with SVGs, but with how fragments work in reveal.js

you’ll have to use [this information](https://github.com/hakimel/reveal.js#fragments).

for SVGs that maybe means  nested groups (`<g class="fragment"><g class="fragment">...</g></g>`)

**Comment by ilpepe** [comment]
owkay. So If i understood right the only thing i need to do is then add the data-src-svg.js file to my dependecies iin the end of the reveal.js stuff:
{ src: 'fill:///Path/to/src/data-src-svg.js', async: false },; }    

and use <svg data-src ... ></svg>

but that doens't seem to work...

**Comment by flying-sheep** [comment]
what does `fill://` mean? and no, you’ll need a bit more.

you’ll need [this version](https://gist.github.com/flying-sheep/3acde57c597a576e7d59) of it, and you’ll need a [fetch polyfill](https://github.com/github/fetch).

**Comment by ilpepe** [comment]
Hi,
Just to complete:
I didn't got this stuff to work, but like i said, that is probably due to my own lack of knowledge.

however I got this going:

<svg viewBox="0 0 500 400">
  <svg class="fragment" data-fragment-index="2" viewBox="0 0 500 400">
    <use xlink:href="images/drawing_plain.svg#layer1">
  </svg>
  <svg class="fragment" data-fragment-index="1" viewBox="0 0 500 400">
    <use xlink:href="images/drawing_plain.svg#layer3">
  </svg>
  <svg class="fragment" data-fragment-index="2" viewBox="0 0 500 400">
    <use xlink:href="images/drawing_plain.svg#layer2">
  </svg>
</svg>


with in the svg the ids set to layer1, layer2, layer3.
i suppose you could even use css with this?
I should also check whether there is a difference between using <g> or <svg>, but for now this is exactly doing what i want...

**Comment by flying-sheep** [comment]
i didn’t think of that. glad that it works for you!

**Comment by rajgoel** [comment]
Hi, I just added a link to a small plugin for svg animation that might be of interest: https://github.com/hakimel/reveal.js/issues/1239#issuecomment-121765373, but above solution looks also very interesting

**Comment by pacharanero** [comment]
@ilpepe thanks for your solution, which works best for me out of the solutions, and I think is perhaps the solution that fits best with a natural workflow for image creation in Inkscape.
So we have this workaround for now, but @hakimel do you think reveal.js might eventually support stepping through the layers of an SVG more 'natively' - eg without having to specify viewbox details? Images are one are where Reveal.js is behind other presentation tools, this is one way to advance that issue.

Something like `<svg class="fragment" svg-data="img/file.svg" svg-layer="1"><\svg>`. I'd submit a PR but my JS is nowhere near good enough.

**Comment by alanafoleykeane** [comment]
Hi, I am trying to animate my SVGs so when we are on the present slide the animation begins.

I have inserted my animations like this:  `<img data-src="pres-assets/svg/03-clip.svg" style="height: 89%; width: 67%;" />`

However the `viewDistance: 5` is loading the slides before hand and setting them to display: none - which mines my SVG animation have already ran before the slide becomes .present.

Has anyone found a workaround for this please?

**Note:** _All my CSS animation keyframes are saved within each SVG file and then inserted as an img in my html._

**Comment by pres-luca** [comment]
I'm not sure if anyone will even discover this thread again since it's so old, but I have the exact same problem as @hadim : I want to show elements of a slide only after I clicked forward or space or anything. I tried @flying-sheep 's script but the svg doesn't even show up. I can only display the file when I don't use the <svg> tag but the <img> tag which then makes the data-src-svg not work again. I thought I'd try the reveal.js plugin "anything" but although it seems to support what I am planning I can't get it to work since it has no documentation at all.

**Comment by flying-sheep** [comment]
but the…?

If you have a `<svg data-src="https://a.working/url.svg"></svg>` and your SVG file contains elements with `class="fragment"` it should work. If it doesn’t, I need to see error messages to be able to help you.

**Comment by pres-luca** [comment]
@flying-sheep That `<img>` somehow made the rest of my comment invisible when rendered, I'm sorry & I fixed it now.
My problem is that the `<svg>` tags seem to be not working at all. I used the exact line you quoted with multiple svg files but none of them is showing in reveal.js at all. I don't even think that has got anything to do with your program but I don't really know where else to ask. I am writing my presentation in markdown by the way, don't know if that makes any difference since inline html worked flawlessly for me until now.

**Comment by flying-sheep** [comment]
Sure. Well, it doesn’t work if the `fetch` fails which should appear in the logs …

**Comment by pres-luca** [comment]
@flying-sheep Sorry but I'm not entirely sure where I can find those logs. If that helps: The terminal window in which I ran `npm start` to start the server shows no errors, only the times I changed my markdown presentation file.

**Comment by flying-sheep** [comment]
The network tab of your browser’s devtools will tell you if the SVGs are successfully being loaded.

**Comment by pres-luca** [comment]
Ok so I checked this and there isn't a svg showing up at all. What I noticed tho is that there are errors in data-src-svg.js and also in the anything plugin. I removed those plugins then but the SVG still doesn't appear.
