### ISSUE TITLE
incremental mode show first element by default?

### ISSUE THREAD

**Issue by fommil** [hakimel/reveal.js#1424]
Is it possible to have the reveal.js output show the first bullet point automatically when showing a list with incremental parts?

Also, it would be great if when incrementing through the bullet points, the increment only applied to the first layer of bullets and all their children elements were expanded with it.

e.g.

- top level
  - sub
- foo
  - bar

the slide would initially show

- top level
  - sub

and pressing spacebar would then show

- top level
  - sub
- foo
  - bar

currently, the slide opens blank and requires four spaces to expand fully.

**Comment by demoneaux** [comment]
I believe this can be done with something like:

```html
<ul>

**Comment by snekse** [comment]
I'm not sure this exactly addresses what the OP was asking, or maybe things have changed since 2016.  When the slide loads, the initial state will be blank since 

> The default fragment style is to start out invisible and fade in

It would be great if we could add a class to fragments that we want have appear when the slide first loads.  I thought adding one of the existing classes (`visible` `current-visible` `current-fragment`) might do it, but the JS strips out classes on the slide transition. 

For the example that the OP indicated, he could easily just leave the `fragment` class off the first bullet, but if you want the first fragment to shown when the page first loads, then hidden as the next fragment appears, then that first element has to be a fragment. 

Am I missing an option?
