### ISSUE TITLE
Fragment conflict in markdown.js plugin

### ISSUE THREAD

**Issue by i5ar** [hakimel/reveal.js#1443]
Fragment has conflicts if we insert some tags directly in markdown.
The following markdown has conflicts:

> Span-level HTML tags like `<span>`, `<cite>`, or `<del>` can be used anywhere in a Markdown paragraph, <span>list item,</span> <span>or header.</span>

These conflicts can be solved using both `<code>` and <code>&#0096;</code> to wrap the tag but then in the HTML we have double nested `<code>` tags:

> Span-level HTML tags like <code>`<span>`</code>, <code>`<cite>`</code>, or <code>`<del>`</code> can be used anywhere in a Markdown paragraph, <span>list item,</span> <span>or header.</span>

I also tried using `&lt;` and `&gt;` but it would be cleaner with just the appropriate <code>&#0096;</code> to wrap the tags.

**Comment by demoneaux** [comment]
I believe this is because you are placing the Markdown with HTML elements in the `<section>` tag itself. This will cause issues as browsers will parse the HTML before marked, which can lead to inconsistent rendering. To prevent browsers from parsing the Markdown, you should place it in a script template:

```html
<section data-markdown>
<script type="text/template">
## Markdown

<span>...</span>
</script>
</section>
```
