### ISSUE TITLE
some issue about export to pdf

### ISSUE THREAD

**Issue by M2shad0w** [hakimel/reveal.js#1492]
### if i set the theme default(black), and export the html to pdf. i can't see the words in the pdf as follows，and i set the theme(white), it seems ok.
**ps(the content of the html is same).**

anyone knows,thanks

* not see words
![image](https://cloud.githubusercontent.com/assets/3387446/12571381/7c3beb4a-c41b-11e5-9538-4dc9fb120b82.png)

![image](https://cloud.githubusercontent.com/assets/3387446/12571514/f614911e-c41c-11e5-8184-3462b01653a9.png)

* it's ok
![image](https://cloud.githubusercontent.com/assets/3387446/12571437/2d0205ae-c41c-11e5-912e-50b921fe1c64.png)

**Comment by hakimel** [comment]
Printing the black theme works in the demo at http://lab.hakim.se/reveal-js/?print-pdf

Can you try that and let me know if it works for you?

**Comment by M2shad0w** [comment]
@hakimel thanks . 
it don't work for me
![image](https://cloud.githubusercontent.com/assets/3387446/12575940/681976de-c44b-11e5-9570-38a3579d8cab.png)

**Comment by hakimel** [comment]
I think the problem is you haven't checked the "Background graphics" option in the print settings. Not sure what this translates to but I've attached a screenshot where you can see the option in the bottom left.

<img width="994" alt="screen shot 2016-01-26 at 10 13 55" src="https://cloud.githubusercontent.com/assets/629429/12576664/a57a4c32-c415-11e5-8e1f-f2a2fb2f9617.png">

**Comment by M2shad0w** [comment]
@hakimel  thanks, it's the reason!
