### ISSUE TITLE
Split "index.html" into multiple files and support a layout file

### ISSUE THREAD

**Issue by maxmeyer** [hakimel/reveal.js#1539]
I'm quite happy using `reveal.js` itself. Unfortunately I regularly need to build "larger" presentations. Using HTML - but also Markdown - it becomes a little bit confusing/unreadable with all those "sections" in just a single HTML-file.

I found a declined PR (https://github.com/hakimel/reveal.js/pull/429) where someone integrated Jade into `reveal.js`' code base. That's not exactly what I had in mind, but:
- having a separate directory for the slides
- the possibility to place each slide in a separate file - multiple slides per file would be great as well
- some kind of a layout to place the rest of the index.html in - or even make the index.html the layout

Is this possible? Would that something we/you can add to `reveal.js`. To get this kind of things I wrote [`middleman-presentation`](https://github.com/fedux-org/middleman-presentation). 

_Unfortunately_
- it's broken now due to rubygems dependency problems so I need look for possibilties how to solve this situation.
- it's a ruby library where reveal.js is a javascript one
- needs to have installed bower and the like installed along itself (+ npm)

The things mentioned above are the most useful ones for me. With those added to `reveal.js`-core I could abandon `middleman-presentation` and concentrate on other projects - like [cucumber/aruba](https://github.com/cucumber/aruba) - Just to give you a little bit background for my feature request.

Thanks a lot.

Cheers,
Dennis

**Comment by Delapouite** [comment]
Hi @maxmeyer 

Have a look at this project : https://github.com/byteclubfr/prez
It generates reveal.js presentations from a set of independent markdown files. It's made in JS.

**Comment by datavectors** [comment]
I have just started using reveal.js.   
I'm serving reveal.js via apache2/php server on Ubuntu 14.04.
It seems that as alternatives to prez mentioned in @Delapouite post there are several methods which can be used to break up the html code into modules.

The simplest method I've found is using the external plugin.
The modules folder referred to in this plugin's README.md is placed in the root folder of the server.
Sections are then placed in separate files.

Another method is to use php script to echo all or parts of section content.

Currently I'm deploying reveal.js via laravel 5.2 in apache2/php so that I can use laravel blade templates. A laravel project is created by composer.

With php I can also personalise presentations using variables to amend slide content based on user id.
Overall a very useful framework.

**Comment by gbirke** [comment]
I regularly use Jade (now called [Pug](https://github.com/pugjs/pug)) to generate my HTML. And If you're using the full reveal.js package you also need to use npm. 

Here is an example: https://github.com/gbirke/intro-to-ansible-presentation

Your use case can be done with Pug by creating a file named `layout.pug` that conations the HTML and reveal.js boilerplate. Then a file called `index.pug` that extends `layout.pug` and conations include statements for your sub-slides.

**Comment by demoneaux** [comment]
This should probably be handled by a plugin. Looking at the [plugins page](https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware), there appears to be a library, [external](https://github.com/calevans/external), which allows you to import external HTML files, which might be what you’re looking for.
