### ISSUE TITLE
reveal.js with iframes crashes edge and firefox browsers, OK on chrome.

### ISSUE THREAD

**Issue by snassr** [hakimel/reveal.js#1546]
no changes, using iframes linked to the go playground maybe the only thing outside the default - not much customization to the package at all.

repo: https://github.com/snassr/presentation_go_intro
website: http://snassr.github.io/presentation_go_intro

**Comment by hakimel** [comment]
Can you try it without the iframes and let me know if it's still broken? Could be something outside of reveal.js that's breaking.

**Comment by snassr** [comment]
Yes the iframes are the problem. When iframes are included within a reveal presentation, It crashes all browsers except for chrome, which functions normally.

**Comment by jdalton** [comment]
Hiya! Just wanted to ping in and let you all know I'm looking into this from the MS Edge side.

**Comment by Jmuccigr** [comment]
Another data point: the site given above locks up FireFox on my ElCap macbook pro, but Safari (9.1.2) handles it just fine.

**Comment by jdalton** [comment]
Do you know if there's a loop somewhere that may cause issues? I'm seeing the tab get hungup in a loop body.

**Comment by jdalton** [comment]
Looks like a lot of remove child, append child, and set innerhtml is being done in that loop

**Comment by jdalton** [comment]
\cc @bzbarsky

**Comment by jdalton** [comment]
If I replace the https://play.golang.org/ iframes with a src like https://lodash.com/ things work. This makes me think it's something on https://play.golang.org/.

Sample iframe src:
https://play.golang.org/p/ZGmpjak_7O

**Comment by jdalton** [comment]
I also noticed if I remove all but one of the iframes pointing to `play.golang.org` and then have the url jump directly to the slide it avoids a freeze.

**Comment by bzbarsky** [comment]
Looks to me like we end up in a loop in https://play.golang.org/static/jquery-linedtextarea.js in this bit (lines 15-20):

			while (linesDiv.height() <= h) {
				linesDiv.append("<div>" + lineNo + "</div>");
				lineNo++;
			}
			return lineNo;

I just let it spin for a few second and looked at the JS stack, which shows things like:

    2 .domManip(a = <div>58112</div>, c = true, d = [function]) ["https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js":2]

that is, lineNo is up to 58112 and increasing pretty quickly; it was at about 54000 a second earlier.

**Comment by jdalton** [comment]
Nice!

> Looks to me like we end up in a loop in https://play.golang.org/static/jquery-linedtextarea.js in this bit (lines 15-20):
```js
        while (linesDiv.height() <= h) {
            linesDiv.append("<div>" + lineNo + "</div>");
            lineNo++;
        }
```

That describes what my dev buddy [was seeing](https://github.com/hakimel/reveal.js/issues/1546#issuecomment-244212372).

**Comment by bzbarsky** [comment]
OK, so jQuery 1.8.2's `.height()` does `elem.offsetHeight`.  That returns 0 in this case, because the element has no CSS box.  Then it tries `curCSS` which tries to do computed style but doesn't manage to, because the iframe involved is `display:none` (at a guess; I have not verified this) and https://bugzilla.mozilla.org/show_bug.cgi?id=548397 is present.  Then it does:

		if ( val < 0 || val == null ) {
			val = elem.style[ name ];
		}

but of course val == 9, so that block is not entered.  So it ends up returning 0, and the loop never terminates.

Even if https://bugzilla.mozilla.org/show_bug.cgi?id=548397 is fixed it's not clear to me that this would terminate, because it's not clear to me whether the div in question actually has any styles specified.  And the obvious fix for https://bugzilla.mozilla.org/show_bug.cgi?id=548397 would _not_ give the div a CSS box, so if it has no height specified it would end up with something like "auto" anyway, and return 0 from `height()`.

**Comment by jdalton** [comment]
> . Then it tries curCSS which tries to do computed style but doesn't manage to, because the iframe involved is display:none (at a guess; I have not verified this) and https://bugzilla.mozilla.org/show_bug.cgi?id=548397 is present

This explains why it works jumping directly to the slide (when there's only 1 in the deck) because it then shows it and it can calculate the height.

**Comment by jdalton** [comment]
@hakimel This issue can be closed as it' not a reveal.js bug.

**Comment by hakimel** [comment]
@jdalton Gotcha – thanks for looking into it.
