### ISSUE TITLE
ids that starts with a number

### ISSUE THREAD

**Issue by AndreasMadsen** [hakimel/reveal.js#1655]
As I understand it HTML5 does not set any restrictions on the ID (other than it is unique). Thus I can have an id like `2d` and get the hash `#/2d`. In that case https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L3285-L3286 will cause it to be parsed as `2` moving, thus navigating to horizontal slide number two.

I don't know what the correct fix is. But it was confusing very when I had my `2d` slides as `hindex = 3` and when I pressed right it would navigate back to `hindex = 2`.

**Comment by deitch** [comment]
I just got bit by this. Putting together a slide on cloud architectures, wanted a slide on 12-Factor Apps, so I did:

````html
<section id="12factor">
<!-- lots of content here -->
</section>
````

It wouldn't go to it, just jumped over and got stuck. Took me a while to figure out the problem was starting the ID with a number. It violates html4 per https://www.w3.org/TR/html4/types.html#type-id but since reveal.js is html5, where it is allowed to start with a number (or even be _just_ numbers) per https://www.w3.org/TR/html5/dom.html#the-id-attribute it should work.
