### ISSUE TITLE
Why is there a dependency on express, socket.io etc.?

### ISSUE THREAD

**Issue by oncletom** [hakimel/reveal.js#1723]
Hello,

as I installed `reveal.js` from npm, I noticed it installed `express`, `socket.io`, `mustache` and `underscore`.

I assume this is for development purposes, or for a demo so shall we have to fetch these dependencies whereas `reveal.js` primary goal is to be added in the browser?

Thanks :-)

**Comment by simonauner** [comment]
1. I don't think that `npm install reveal` is supported by this repository as it is published to npm by another person than hakimel. (https://github.com/ForbesLindesay/reveal is the npm module)
2. If you read the documentation for "Full setup" you can see that in order to get speaker notes working you need to run reveal.js from a server. https://github.com/hakimel/reveal.js#full-setup

**Comment by hakimel** [comment]
Hey! @simonauner is right that those dependencies are there to support the server side speaker notes and multiplexing functionality.

**Comment by oncletom** [comment]
Oh! It was unclear because this bit is missing — I was not interested by the full setup but only the client-side library. Thanks for the explanation :-)
