### ISSUE TITLE
Big lag time between slides ( with thousands of slides)

### ISSUE THREAD

**Issue by jtkeyva** [hakimel/reveal.js#1742]
I have a couple thousand slides that all have images and videos in them. Everything is snappy with just a few hundred slides but it starts to get really slow with size. 

Once the autoSlide duration is up, it just seems to hang for several seconds before moving on to the next slide. Any ideas how to fix this?

Thanks

**Comment by jocelynlecomte** [comment]
Do you realize that all your slides land in the same page ? I don't think reveal.js is made for such huge prez. You should probably consider splitting it in several smaller prez.

**Comment by jtkeyva** [comment]
Thank you, yes but how would you recommend doing that? Could it be as seamless and transparent to the viewer/end user? Kinda like an infinite scroller. Any ideas appreciated, thanks!

**Comment by jocelynlecomte** [comment]
It would mean that slides are loaded when needed. It's not the way reveal works for now, and I don't know any plugin doing that. I guess this is because that would mean that a server is needed for the prez to show. Maybe you could submit a request for this feature, but it would anyway take some time to be implemented. The quickest answer is to break your huge prez into several smaller prez, which should be fairly easy.

**Comment by jtkeyva** [comment]
Gotcha, thanks alot!
