### ISSUE TITLE
Allow customization of speaker notes

### ISSUE THREAD

**Issue by pmlopes** [hakimel/reveal.js#1775]
Sometimes if one needs to present and is not really close the the speaker notes laptop the small bottom right area where the notes are shown get hard to read.

I'd say that it would be nice to be able to switch the notes area with the main left area for the case when you're a bit too far from your screen.

Sure the main deck will be smaller but probably you already know what is there and you might be able to see the main projection during the talk...

**Comment by malcomio** [comment]
I agree - I've ended up changing the styling and markup of https://github.com/hakimel/reveal.js/blob/master/plugin/notes/notes.html in order to change the sizes.

When I get time, I intend to tidy up my changes and create a pull request for it. 

For now, here are the changes I've made:
https://github.com/malcomio/presentations/commit/208c4fda95cd4340e17e601bfacddbfd46a036a6
https://github.com/malcomio/presentations/blob/gh-pages/plugin/notes/notes.html

**Comment by pmlopes** [comment]
There's a switch in the speaker notes that offers what I was asking
