### ISSUE TITLE
PhantomJS plugin for PDF printing doesn't work in relesease 3.4.0+

### ISSUE THREAD

**Issue by asanzdiego** [hakimel/reveal.js#1815]
Hi:

The [PhantomJS plugin](https://github.com/hakimel/reveal.js/blob/master/plugin/print-pdf/print-pdf.js) of @manuelbieh for PDF printing doesn't work in [relesease 3.4.0+](https://github.com/hakimel/reveal.js/releases/tag/3.4.0)

Thanks for all.

**Comment by hakimel** [comment]
I've rewritten the script to work with 3.4.0. The updated script will preload the presentation and read the configured width/height from reveal.js directly so that we can use that as the PDF page size. This makes it work with any configured size and removes the old "width" and "height" arguments from the phantom script.

**Comment by asanzdiego** [comment]
Thanks @hakimel. I will try the last relase ¿3.4.2? in my own proyect [MarkDownSlides](https://github.com/asanzdiego/markdownslides) \o/

**Comment by hakimel** [comment]
No problem. There's no new release yet, but the updated script is available in master.

**Comment by asanzdiego** [comment]
I've tested it and it seems to work fine. :) But I can't upgrade my [proyect](MarkDownSlides) until you do a release :( Thanks a lot anyway \o/
