### ISSUE TITLE
Reveal slides not indexed by search engines

### ISSUE THREAD

**Issue by stephane-caron** [hakimel/reveal.js#1824]
Hi there,

I noticed when I search for the title of my presentations on Google/Yahoo/Bing/etc. that my slides made with reveal.js are not indexed by search engines, while the HTML page pointing to the slides ranks first in all searches (meaning robots have crawled the content). ([Example](https://scaron.info/research/humanoids-2016-talk.html).)

Is there a way to make search engines index slides made with reveal.js?

If not, I might revert to PDF, which is a *de facto* standard and well-crawled by all major search engines.

Best,

**Comment by demoneaux** [comment]
There doesn't seem to be a reason why search engines don't index Reveal slides. In fact, the top result for Reveal on Google is http://lab.hakim.se/reveal-js/, which are the demo slides. Perhaps you should modify your meta tags and add some such as description, author and keywords. (I'm not too good at SEO, so you should probably consult some other resources for more help).

**Comment by mef** [comment]
You may use Google search console's ["fetch as Google" feature](https://www.google.com/webmasters/tools/googlebot-fetch) in order to check how googlebot sees your pages.

For reveal.js slides, apparently, google only considers the first slide as visible content. I guess that the content from the other slides have way less weight as ranking factors...
