### ISSUE TITLE
MathJax Latex macros local.js configuration file

### ISSUE THREAD

**Issue by cgrudz** [hakimel/reveal.js#1946]
I would  like to load my own Latex macros and additional options in MathJax from a local configuration file, as instructed on:

http://docs.mathjax.org/en/latest/tex.html#defining-tex-macros

However, I'm having an issue when I try to load multiple configuration files in Reveal.  For instance, running the script

```
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
    TeX: { equationNumbers: { autoNumber: "AMS" } }
    });
</script>
```

in the body of my presentation provides equation numbering as desired.  On the other hand, if I include the following
```

MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});

MathJax.Ajax.loadComplete("[MathJax]/config/local/local.js"); 

```
in my local.js file, and load MathJax from a local directory in Reveal as

```
Reveal.initialize({
	math: {
                   mathjax: '/home/plinx/Dropbox/Documents/scripting/MathJax/MathJax.js',
                   config: 'TeX-AMS_HTML-full, /local/local.js'
            },
```

it loads the 'TeX-AMS_HTML-full' configuration fine, but it doesn't load the additional options in the local.js file, and there are no equation numbers.

Is it possible to load multiple MathJax configuration files as such? 

Thanks for your support!

**Comment by bnjmnt4n** [comment]
Looking at http://docs.mathjax.org/en/latest/configuration.html#using-a-configuration-file, it seems like you should use a full URL when naming your `config`, eg. `config: 'TeX-AMS_HTML-full,https://mysite.com/local/local.js'`, with no space between the 2 config files. Additionally, instead of using `MathJax.Ajax.loadComplete("[MathJax]/config/local/local.js");`, you might have to put the full URL of the config file instead of using `[MathJax]`.
