### ISSUE TITLE
Remove reveal and initialize again

### ISSUE THREAD

**Issue by OscarDeDios** [hakimel/reveal.js#1948]
Hi.

I'm using reveal in a web app dynamically.  I create the sections and I do the initialization. It works well but with ESC I want to remove the slide show and later create other sections for a new slide show.

I tried to remove the DIV with $('.reveal).remove() and then I create the DIV again. But the second time the initialize doesn't work and the elements don't have the reveal classes neither the arrows etc... It's like the reveal object was associated to the first .reveal DIV and I couldn't creat the object with the new DIV.

How can I do this?  

Thanks.

Oscar.

**Comment by xyng** [comment]
Try using Reveal 3.3.0. Calling `Reveal.initialize(...)` again will not break your app and `Reveal.sync()` will update the slides.
I'm currently figuring out what's the problem there as I'd like to make use of the pdf-export improvements - will report back as soon as I'll find something.

**Comment by xyng** [comment]
Allright, that was a quick find! Unfortunately, they now prohibit re-initialization (see: https://github.com/hakimel/reveal.js/blob/568c7516f7ff7da7824db033946619d2c7ad761f/js/reveal.js#L264) since 3.4.0.
The problem - with our app at least - seems to be that we exchange the whole .slides div when changing to another presentation, but the internal dom.slides is still the old one. Since re-initialization is not possible anymore (but why?) there is no way to set that to the new one. This results in the new slides not being used (they don't get the necessary classes).

**Comment by bnjmnt4n** [comment]
Initializing something twice is a bad practice, and may cause unexpected side effects, especially since Reveal does so much DOM manipulation. In your case, deleting the whole `.reveal` slide is a bad idea as Reveal does not re-attach to the new `.reveal` class. What you should do is delete the slides and re-add them later and call `Reveal.sync()`.

**Comment by h-tendy** [comment]
Hi @bnjmnt4n  - I tried what you suggested, but it still doesn't do the right thing. That is, the `sync` process messes up the slides. In my application, we are regenerating all the `<section>` tags again inside the slides. 

I'm using 4.1.3. Any inputs appreciated!

**Comment by ibnsultan** [comment]
> Hi @bnjmnt4n - I tried what you suggested, but it still doesn't do the right thing. That is, the `sync` process messes up the slides. In my application, we are regenerating all the `<section>` tags again inside the slides.
> 
> I'm using 4.1.3. Any inputs appreciated!

I am also facing a similar issue as mentioned here, buy the time the sync function is called the first slide becomes discombobulated
