### ISSUE TITLE
Question: Lazy Loading for slide backgrounds?

### ISSUE THREAD

**Issue by robertop87** [hakimel/reveal.js#1981]
Hi @hakimel, thanks for this great tool!

Currently my presentation has 7 videos (average size 250 MB), and I'm using each one as slide background (in order to scale them correctly), when I start the presentation the memory use increases at least 7*250 MB, I think that means all videos are in memory. I read about Lazy Loading https://github.com/hakimel/reveal.js/#lazy-loading, and looks really nice, but the memory uses is still using >7*250 MB. Regarding this I have 2 questions:

1. How can I get the same behaviour for slide backgrounds https://github.com/hakimel/reveal.js/#slide-backgrounds?
2. If I don't use the lazy loading, I should assume that all media will be loaded in RAM, is this a matter related with the RevealJS or the Browser Engine?

Thanks in advanced.

**Comment by bnjmnt4n** [comment]
Hi, the videos in the slide background are also lazy loaded, so based on your configured `viewDistance`, slides which are within the configured slides away will have their background videos begin to load. If you don't want to buffer so much video at once, you can try reducing the `viewDistance` although that might increase load time of slides. After a video is shown and the slides are changed, the video is then removed. In this case the RAM usage might just be due to the browser engine, and memory usage should decrease in time.
