### ISSUE TITLE
Deprecation warnings when doing a full install.

### ISSUE THREAD

**Issue by cschwenz** [hakimel/reveal.js#2073]
After cloning `reveal.js` (`HEAD` was at commit a0c013606e130baad976195730dcd7e7cd9e2855), the below deprecation warnings were issued when I followed the full install instructions:

```
% npm install                                                                                                               (master|✔)
npm WARN deprecated http2@3.3.7: Use the built-in module in node 9.0.0 or newer, instead
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

[...]
```

**Comment by bnjmnt4n** [comment]
This is due to our usage of Grunt as a task manager, and `grunt-contrib-connect`. Grunt hasn't been updated in 2 years, and some of its dependencies are probably outdated. I've created an issue here: https://github.com/gruntjs/grunt/issues/1618. Also for `grunt-contrib-connect` see https://github.com/gruntjs/grunt-contrib-connect/issues/235. But regardless, both these warnings should not affect users directly.

**Comment by graingert** [comment]
@bnjmnt4n might be worth investigating using webpack
