### ISSUE TITLE
Can you explain how to present using projector

### ISSUE THREAD

**Issue by s1291** [hakimel/reveal.js#2146]

**Comment by VladimirAlexiev** [comment]
You need two video outputs. Eg on my laptop, in addition to showing on the builtin screen, I use VGA or DVI video output connected to the projector.

**Comment by VladimirAlexiev** [comment]
1. Cause Ubuntu to show "extended" desktop on the two screens. I don't know how to do this since I use Windows
2. Press "S" in reveal to show the Presenter window (see https://github.com/hakimel/reveal.js#speaker-notes)
3. Move the new window to another screen. In Chrome you drag the tab to split it off from the main browser window

**Comment by lechten** [comment]
Maybe your Laptop has "function keys" or "hotkeys" (e.g., Fn in lower left of keyboard to be pressed simultaneously with one of the numbered function keys such as F7). If your Ubuntu is compatible with your hardware, repeatedly pressing that key combination switches between display only, VGA only, VGA on extended screen etc.
Alternatively, this may help: https://help.ubuntu.com/stable/ubuntu-help/display-dual-monitors.html
Or that: https://askubuntu.com/questions/29797/how-can-i-extend-the-desktop-onto-an-external-monitor-projector

**Comment by reagle** [comment]
This should be closed.

**Comment by grico95** [comment]
Yes 👍🏼👌
