### ISSUE TITLE
GitLab Snippets Support

### ISSUE THREAD

**Issue by mccarthyryanc** [hakimel/reveal.js#2247]
I'm trying to put a [GitLab snippet](https://gitlab.com/snippets/1759505) into a slide via script tags:
```html
<section>
  <script src="https://gitlab.com/snippets/1759505.js"></script>
</section>
```
Which displays as:
![image](https://user-images.githubusercontent.com/997120/46423396-4b6f4e00-c6eb-11e8-8523-c30390330ea6.png)

Just for comparison, if I put a similar GitHub Gist into a slide:
```html
<section>
  <script src="https://gist.github.com/hakimel/c7b71eb214b29cb180aa.js"></script>
</section>
```
Things render properly:
![image](https://user-images.githubusercontent.com/997120/46423521-9a1ce800-c6eb-11e8-9882-368a4f8cb320.png)

**Comment by bnjmnt4n** [comment]
HI @mccarthyryanc! This is due to Gitlab snippets using the same `pre code` blocks which are highlighted by the highlight.js plugin. There doesn't seem to be a good solution for this, except perhaps adding the `no-highlight` class to the `pre code` yourself. GitHub Gists don't suffer from the same problem as they don't use `pre code` to display code, instead choosing to utilise a `table` to display code.
