### ISSUE TITLE
Markdown: Nested lists do not work

### ISSUE THREAD

**Issue by MurhafSousli** [hakimel/reveal.js#2309]
Trying this when using markdown and it only show one level list not nested

```markdown
- Get everyone on the same page
- Introductions to:
  - HTML
  - Version control
  - Cascading Stylesheets (CSS)
- Understanding online documentation
```

**Comment by retokromer** [comment]
This:
```
- Get everyone on the same page
- Introductions to:
  - HTML
  - Version control
  - Cascading Stylesheets (CSS)
- Understanding online documentation
```
just gives that:
- Get everyone on the same page
- Introductions to:
  - HTML
  - Version control
  - Cascading Stylesheets (CSS)
- Understanding online documentation

**Comment by MurhafSousli** [comment]
I mean in the reveal.js, not here in the Github issue comments!

**Comment by mauvilsa** [comment]
I was having the same issue with pandoc and reveal.js so ended up here. After trying few things I noticed that if I indent the nested list with four spaces instead of two it works. I comment here since it can be useful for other people.

**Comment by MurhafSousli** [comment]
Thanks, that also worked for me.

**Comment by lucidBrot** [comment]
For anybody else finding this issue because it seems that nested lists don't work in the Notes: Turns out that the speaker view does not auto-update the notes even if the slides do update themselves when you change them. So I thought it was not working for me, but it actually was working. I just had to close and reopen the speaker view.
