### ISSUE TITLE
Search plugin with strange default

### ISSUE THREAD

**Issue by lechten** [hakimel/reveal.js#2331]
The search plugin applies a regular expression in [line 33](https://github.com/hakimel/reveal.js/blob/master/plugin/search/search.js#L33) to change the input string. Non-word characters at the beginning and end are removed. Why? Also, hyphen and non-word characters are replaced by alternatives. Again, why? For example, "I/O" will match all words containing "i" or "o". Also search for words with hyphens and multi-word phrase search do not work. What about removing that line?

**Comment by t-fritsch** [comment]
Thanks for the ping in #3492 😉

This is a good question (that I've asked myself while doing the PR for #3492 😅) and I have no idea of why this is done this way. I've searched the commit history but it seems this behavior is in place since the very first commit : https://github.com/hakimel/reveal.js/commit/8d61a112ff6bbf4a165a5706325dc673c6fd40d5 
Maybe @hakimel or @razor-1 (who did this first commit) remembers why ?

I never use search but I also think that it'd be better if it tried to match any input, not only alphanumeric chars (at the moment anything that is not alphanumeric/single quote `'`/and minus`-` is replaced by a logical 'OR' (`|` in the regexp), splitting the search in two (ie. searching for `'aa_bb'` will search for `aa` and `bb`) maybe having only whitespace character considered as a `|` would be better ?

**Comment by lechten** [comment]
Thanks for replying here! Why should alternatives be introduced at all? Why not allow phrases?

If alternatives are desirable, they could be supported and documented explicitly, say "foo|bar".

**Comment by hakimel** [comment]
This seems like an odd limitation. I've changed it so that we search for the full input phrase. The only remaining modification is a trim. Thanks for looking into this @t-fritsch!

**Comment by lechten** [comment]
Great, many thanks for fixing this!
