### ISSUE TITLE
Why shouldn't lazy-loaded iframes preload?

### ISSUE THREAD

**Issue by maxrothman** [hakimel/reveal.js#2352]
Looking at [this line](https://github.com/hakimel/reveal.js/blob/0b3e7839ebf4ed8b6c180aca0abafa28c67aee6d/js/reveal.js#L3721), if an iframe is contained in a fragment and has the `data-src` attribute, it won't be loaded until its containing fragment is visible. That means that when the fragment becomes visible, the page will begin visibly loading onscreen in the middle of the presentation. What was the intention behind this behavior? Why shouldn't iframes in fragments be preloaded per the viewDistance and simply hidden like non-fragment iframes? Would you be open to changing this behavior or adding an option for it?

FWIW I've worked around this behavior by simply not lazy-loading iframes.

**Comment by hakimel** [comment]
We don't preload iframes the same way since they are often used to embed autoplaying video, audio, or other similar content.

In those cases you'd end up hearing the audio of something that isn't visible yet. Even if it's a muted video player, if it autoplays it would be playing while invisible so that viewers would be missing out on some of the content.

One more consideration is that iframes can be used to pull in performance heavy content which you don't always want running in the backgrounds. For example, I embed a lot of visual canvas experiments in my talks and having multiple of those load at the same time would cause the computer to 🔥

That said it might be interesting to add an option for changing this behavior, on a per-iframe bases.

**Comment by maxrothman** [comment]
First, I realize I had the line wrong. The correct piece of code is [this one](https://github.com/hakimel/reveal.js/blob/0b3e7839ebf4ed8b6c180aca0abafa28c67aee6d/js/reveal.js#L3729-L3739
).
 
I understand why one wouldn't want to load iframes until they're in view if they contain media, but in that case why are iframes pre-loaded if they're _not_ in a fragment? The thing I'm confused about is why fragments are a special case. I'd think you wouldn't want media iframes loading on non-visible slides either, but they do as per the `viewDistance` config.

I'm happy to contribute this feature either way.

**Comment by hakimel** [comment]
Lazy loaded `data-src` iframes aren't preloaded according to `viewDistance`. They load when their containing slide becomes visible and unload again when it's hidden.

Maybe we can add a `<iframe data-preload>` attribute that flags that the given iframe should be loaded according to `viewDistance`?

**Comment by maxrothman** [comment]
> Lazy loaded data-src iframes aren't preloaded according to viewDistance. They load when their containing slide becomes visible and unload again when it's hidden.

Hm, that sounds like an update to the readme is in order as well.

> Maybe we can add a <iframe data-preload> attribute that flags that the given iframe should be loaded according to viewDistance?

I'll put up a quick PR for that and the doc updates.
