### ISSUE TITLE
Up-arrow not highlighted, down-arrow disappears in reveal.js demo

### ISSUE THREAD

**Issue by PenelopeFudd** [hakimel/reveal.js#2377]
Hi;
This is my first visit to Reveal.js, and I think I've found a bug: the up-arrow icon doesn't light up when it should, and the down-arrow disappears instead of being dimmed.

How to reproduce:
1) Go to https://revealjs.com/#/
2) Go right, right, down; you should be on the slide titled "BASEMENT LEVEL 1"
The down arrow is light blue (active), but the up arrow is dark blue (disabled), even though you can go up.
3) Go down again; you should be on the slide titled "BASEMENT LEVEL 2"
The down arrow disappears, but the up arrow is still dark blue (disabled).

Actually, I'm no longer sure what the colors mean.  

It initially looked like they meant enabled/disabled, but it now appears that disabled arrows are invisible.  
Then I thought it might mean visited/unvisited (like plain html links), but that's not the case either, as they haven't changed colors since I've been here.

There's 353 open issues in the queue, it's likely that this issue will gather dust, but thanks for reading this far, whoever you are.  :-)

**Comment by hakimel** [comment]
Hey! That's not a bug. Arrows that lead to previous slides are de-emphasized (faded out) since the user is more likely to want to progress forwards through the deck. When there are four equally prominent arrows it gets harder to understand where to go/how to navigate. Arrows pointing in a direction where you can't navigate are hidden.

You can control and change this behavior using the `controlsBackArrows` config option. See https://github.com/hakimel/reveal.js#configuration
