### ISSUE TITLE
head.min.js missing

### ISSUE THREAD

**Issue by berney** [hakimel/reveal.js#2396]
When I load slides produced with revealjs master, or 3.8.0, I get an error about `lib/js/head.min.js` being missing (404). I don't get this error with 3.7.0 as the file still exists.

Are we meant to include some dependencies, or should something be cleaned up to stop referring to head.min.js >= 3.8.0 that no longer has that file?

**Comment by hakimel** [comment]
`head.min.js` is no longer included or required since reveal.js 3.8.0. I double-checked but I can't see it referred to from anywhere inside the repo. Let me know if you see it being referred to from somewhere I've missed.

**Comment by moesphere** [comment]
I am having the same problem. I am converting using `jupyter nbconvert`, just changing the `reveal_url_prefix` option from 3.7.0 to 3.8.0. Works with 3.7.0, but does not work with 3.8.0 when I open the slides html file. However, that is probably related to the `nbconvert` function. The `--post serve` option does not work for both btw.

**Comment by grosscol** [comment]
`jupyter nbconvert` uses pandoc to generate it's reveal.js presentations.

This was an issue caused by pandoc-templates for pandoc 2.7.2.  The [default.revealjs](https://github.com/jgm/pandoc-templates/blob/64a929d7eec7f2c0b741433b30d6b904354a4e74/default.revealjs#L91) template included the reference to `head.min.js`.  This was [corrected](https://github.com/jgm/pandoc-templates/blob/db59a5e77b0a5629f0801eb82103814842f2e2ed/default.revealjs#L91) in pandoc-templates 2.7.3 and on.

Update pandoc.

**Comment by fbeve** [comment]
Hi, I am using a presentation done by someone else. I get the errors in firefox console : 
Loading failed for the <script> with source “file:///lib/js/head.min.js”. index.html:31:1
Loading failed for the <script> with source “file:///js/reveal.js”. index.html:32:1

These two files are not in the repo of directory I cloned. 
So they are missing.
Can someone tell me if adding these 2 files in the appropriate directory might solve the issue ? or does it appear to be a different issue ?

**Comment by grosscol** [comment]
@fbeve the first file missing is related to this issue, but shouldn't be a problem as head.min.js is no longer used by reveal.

The missing reveal.js is not this issue.  Sounds like you didn't clone the submodules of the repo.  `git clone --shallow-submodules --recurse-submodules` might fix your issue.
