### ISSUE TITLE
Rendering React components in a slide?

### ISSUE THREAD

**Issue by slnovak** [hakimel/reveal.js#2565]
Hello!

I'm interested in being able to render React components within a slide so that a user can transition between separate React apps as part of a presentation.

I've looked around to see if this has been done, but haven't found any examples. Do you know of any existing implementations that do this?

If not, would it be feasible to implement this as a plugin? (I'm not quite sure what that would look like, given Reveal.js's design/architecture.) I'd be happy to implement it if someone can point me in the right direction.

Thanks!

**Comment by slnovak** [comment]
I just came across the [Anything Plugin](https://github.com/rajgoel/reveal.js-plugins/tree/master/anything) -- I think this may allow me to mount a React app in a slide.

**Comment by slnovak** [comment]
Quick update!

I ended up taking a different approach to my original problem, so this issue doesn't need to remain open.

In my poking around, I ended up forking the repo, adding Webpack to the dev dependencies (along with grunt-webpack), and using the babel-loader library to transpile React code embedded in Reveal slides. But at that point, I had to pivot to take a different approach to the problem I was trying to solve, so I abandoned pushing forward down that path.

I'm happy to re-open this issue if anyone come across a similar use-case.

Cheers!

**Comment by Shaker-Hamdi** [comment]
Hello @slnovak I'm having the same issue, how did you manage to solve this?

**Comment by slnovak** [comment]
Hi @Shaker-Hamdi -- I didn't work on the problem past what I posted above. I think it's possible to do -- you just have to conform to the current project configuration. Babel will be needed to leverage `@babel/preset-react` (so you can use JSX components). You'll also need to hook up Webpack so that you can bundle up your app for it to be served. Once you get those two set up, it shouldn't be too difficult to get it up and running.

I'm not sure if I have time to work on it at the moment, but I'm happy to answer any questions!

**Comment by bouzidanas** [comment]
For anyone who is still interested in being able to put react components inside Reveal slides, the solution is simpler than expected.

# Manual

Say you have a very simple presentation:
```html
<html>
  <head>
    <link rel="stylesheet" href="dist/reveal.css">
    <link rel="stylesheet" href="dist/theme/white.css">
  </head>
  <body>
    <div class="reveal">
      <div class="slides">
        <section>Slide 1</section>
        <section>Slide 2</section>
      </div>
    </div>
    <script src="dist/reveal.js"></script>
    <script>
      Reveal.initialize();
    </script>
  </body>
</html>
```
The content of the presentation is in the `<div class="slides">` element. 

## React everywhere
If you want to create the contents entirely in React (which you can), then make this div (or preferably the parent div with `class="reveal"`) the `#root` of your React App (using `ReactDOM.createRoot`). Dont forget to add the parts of your presentation's html to your React projects `index.html` that are needed to get the slides to work. For the example above, you would need to add:
```html
<link rel="stylesheet" href="dist/reveal.css">
<link rel="stylesheet" href="dist/theme/white.css">
```
to `index.html`'s head element and add the scripts
```html
<script src="dist/reveal.js"></script>
<script>
  Reveal.initialize();
</script>
```
somewhere at the end of `index.html`'s body element.

## React Islands
However, if you want to only sprinkle in components in specific slides, then I would make the react root element a separate element that sits outside of the reveal container div and then **use [portals](https://react.dev/reference/react-dom/createPortal) to place react component into specific sections.** 

For a simple Vite project you might end up with an `index.html` that looks like:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <link rel="stylesheet" href="dist/reveal.css">
    <link rel="stylesheet" href="dist/theme/white.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React + TS</title>
  </head>
  <body>
    <div class="reveal">
      <div class="slides">
        <section>Slide 1</section>
        <section>Slide 2</section>
      </div>
    </div>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
    <script src="dist/reveal.js"></script>
    <script>
      Reveal.initialize();
    </script>
  </body>
</html>
```

There is one issue with the above and that is the paths for the reveal links and scripts. You need to make sure they are correct and they depend on how you added Reveal to your project. I would recommend using the `npm` installation method and then making sure reveal is included in the build (so it ends up in the `dist` directory).

# Programmatic

Instead of editing/manipulating the `index.html` by hand, you can add and initialize reveal in a react app source file like `main.tsx` or `app.tsx`. You can do it globally outside of app/component functions or inside one of them. In the latter case, you have to be careful not to stack initializations. Only initialize a slide deck once. If you need to reconfigure, use the `configure` function or `destroy` the deck before initializing again.

To begin, install reveal using `npm`:

```bash
npm install reveal.js
```
and to get types for typescript
```bash
npm i --save-dev @types/reveal.js
```

## imports

You will need the following imports:

```ts
import Reveal from "reveal.js";
import "reveal.js/dist/reveal.css";
import "reveal.js/dist/theme/black.css";   // "black" theme
```

Finally, just execute the code provided in the [initialization section of the Reveal.js docs](https://revealjs.com/initialization/). Make sure to use what is relevant to your case.

# react-reveal-slides
I have created a package called [react-reveal-slides](https://github.com/bouzidanas?tab=repositories) for creating reveal presentations entirely in react. It takes care of pretty much everything in the last section for you and allows you to easily create presentations using react components including all of the contents of the presentation. You can make every slide completely dynamic, control the presentation state and more. You can also create multiple presentations. 

The package is still in dev phase (although everything I just mentioned is working) and has not yet been published to `npm`. This means you will have to install it using the repo.
