### ISSUE TITLE
Building CSS themes causes them not to work anymore

### ISSUE THREAD

**Issue by phossen** [hakimel/reveal.js#2694]
Hi,
while migrating from 3.x to 4, I struggled to adopt my custom themes. It turned out to be a general problem of the new version.

Browser: Firefox Version 76.0.1 (64bit) and Chrome
OS: Windows 10

Steps:
1. Clone reveal.js repository
2. `cd reveal.js && npm install`
3. `npm start` and go to e.g. http://localhost:8000/examples/auto-animate.html to check if it's working. Which works perfectly fine.
4. Shut down npm
5. `npm run build -- css-themes`
6.  `npm start` and go to e.g. http://localhost:8000/examples/auto-animate.html to check if it's working. In my case i just get a white screen.  Background, Barebone, Math, Media and Transition seem to work. Layout-helper, auto-animate, and multiple-presentations fail.

**Comment by hakimel** [comment]
Hey. I just tried a new install and went through the steps you outlined but the auto-animate example still worked. It was styled with the correct theme (black).

Were there any errors during the build or in the console when opening the deck? Also would you mind attaching a copy of the generated /dist/theme/bllack.css file? If the presentation is coming up white I'm assuming those styles didn't generate correctly. 

Sidenote; `npm run build -- css-themes` triggered a build of all JS/CSS, not just the themes. I've updated the npm build script in master so that it will support executing specific tasks going forward  though.

**Comment by phossen** [comment]
The small change you just committed fixed my problem!

I had no errors during the build or the opening the deck. The generated black.css: [black.txt](https://github.com/hakimel/reveal.js/files/4751213/black.txt)

Also, reverting all the plugins to the state of the master helped. So the generated css don't seem to be the problem.

**Comment by hakimel** [comment]
Glad to hear it works now. Surprised my commit made a difference. It didn't change how the build itself works, it only made `npm run build` execute `gulp` instead of `gulp build`, but both of those trigger the same gulp tasks 🤷‍♂️

The black.css output seems identical to what I've generated locally so that probably wasn't the issue. Thanks for sending it over.
