### ISSUE TITLE
Markdown inside fragments

### ISSUE THREAD

**Issue by damianavila** [hakimel/reveal.js#275]
I would be great to have markdown rendering in fragment.
I have tested some ideas, but it seems not working properly...
Do you have any insight?

Thanks.

**Comment by tyrcho** [comment]
@wighawag This does not work as well as in remarkjs unfortunately, since it only applies the class fragment to the current element and not to the rest of the slide.

Sample slide content to show the issue (the second quote is displayed immediately) :


# Example : Stream Ranges

```
def streamRange(lo: Int, hi: Int): Stream[Int] =
  if (lo >= hi) Stream.empty
  else Stream.cons(lo, streamRange(lo + 1, hi))
```

--

Which is very similar to 
```
def listRange(lo: Int, hi: Int): List[Int] =
  if (lo >= hi) Nil
  else lo :: listRange(lo + 1, hi)
```

**Comment by tyrcho** [comment]
@hakimel It would be great if you could solve this issue ... I suck at javascript/css so I cannot help much more than testing it ... This is the only thing which restrains me to use reveal.js (and remarkjs has less features unfortunately)
