### ISSUE TITLE
Incorporating reveal.js into a react project?

### ISSUE THREAD

**Issue by princefishthrower** [hakimel/reveal.js#2784]
Searched the open and closed issues, nobody has seemed to have done this or asked about this yet. Does anyone in the community have experience with using reveal.js in a react project or know a decent react wrapper for it? (I found some old react wrappers for reveal.js but most haven't seen any changes in the last 4+ years!)

**Comment by princefishthrower** [comment]
Actually, it works! (At an initial try. Currently, I'm having trouble with getting the slide transition animations to work, but hopefully, it is just a CSS conflict). Here's a most basic react component with hooks example (note that I moved the styles in locally as a quick fix since frameworks like create-react-app do not allow imports from outside the src/ directory!)

```jsx
import * as React from "react";
import Reveal from 'reveal.js';

import '../../styles/reveal.js/reset.css';
import '../../styles/reveal.js/reveal.css';
import '../../styles/reveal.js/theme/white.css';

export function CollectionPresentation() {

    React.useEffect(() => {
        let deck = new Reveal({
            backgroundTransition: 'slide',
            transition: 'slide'
         })
         deck.initialize();
         console.log('initialized fool')
    },[])

    return (
        <div className="reveal">
            {/* Any section element inside of this container is displayed as a slide */}
            <div className="slides" data-transition="slide">
                <section data-transition="slide">
                    <a href="https://revealjs.com">
                        <img
                            src="https://static.slid.es/reveal/logo-v1/reveal-white-text.svg"
                            alt="reveal.js logo"
                            style={{
                                height: "180px",
                                margin: "0 auto 4rem auto",
                                background: "transparent",
                            }}
                            className="demo-logo"
                        />
                    </a>
                    <h3>The HTML Presentation Framework</h3>
                </section>

                <section data-transition="slide">
                    <h2>Hello There</h2>
                    <p>
                        reveal.js enables you to create beautiful interactive
                        slide decks using HTML. This presentation will show you
                        examples of what it can do.
                    </p>
                </section>

                <section data-transition="slide">
                    <h2>Marvelous List</h2>
                    <ul>
                        <li>No order here</li>
                        <li>Or here</li>
                        <li>Or here</li>
                        <li>Or here</li>
                    </ul>
                </section>

                <section data-transition="slide">
                    <h2>Fantastic Ordered List</h2>
                    <ol>
                        <li>One is smaller than...</li>
                        <li>Two is smaller than...</li>
                        <li>Three!</li>
                    </ol>
                </section>
            </div>
        </div>
    );
}
```

**Comment by princefishthrower** [comment]
Also helpful for anyone who comes here. We were also using Bootstrap for our styling, this solution https://github.com/hakimel/reveal.js/issues/1515#issuecomment-432471954 solved the transition issue I mentioned above!

All is well in reveal.js + react.js land!

**Comment by simonbarker** [comment]
i can't get this to work in a react project. it inits fine but the content just sits on the page as if Reveal can't access the dom

**Comment by hyunwoona** [comment]
@simonbarker I had the same problem but got this working. I had to set the width and height of `.reveal`.

**Comment by zxq08** [comment]
令人不解的是，57K+star，居然没几个关于react使用的issues... 暴风哭泣

**Comment by DQinYuan** [comment]
I have an error:

export 'default' (imported as 'Reveal') was not found in 'reveal.js'

anyone know why?

**Comment by SumukhJadhav** [comment]
Yes even I'm having similar issues @DQinYuan

**Comment by kenneho** [comment]
Maybe the walkthrough over at [3488](https://github.com/hakimel/reveal.js/discussions/3488) might be of help.

**Comment by ImJimmi** [comment]
I got this working by having

```html
<div id="root" class="reveal">
```

in my `index.html`, and then

```jsx
function App() {
    useEffect(() => {
        let deck = new Reveal({
            backgroundTransition: "slide",
            transition: "slide",
        });
        deck.initialize();
    });

    return (
        <div class="slides">
            <section>Slide 1</section>
            <section>Slide 2</section>
        </div>
    );
}
```

in `App.js`.

Having the `class="reveal"` in `App()` didn't seem to work for whatever reason.

**Comment by t-fritsch** [comment]
I haven't tested it but I think that adding an empty array as useEffect's [dependencies](https://react.dev/reference/react/useEffect#parameters) might ensure the deck is initialized only once (ie. even if `App` component gets rerendered). 
Also having the `deck` in a [ref](https://react.dev/reference/react/useRef) may be useful to later call methods on it (like `deck.next()`, `deck.getSlide(...)`, etc. see https://revealjs.com/api/) :

```jsx
function App() {
    const deck = useRef(null); // keep deck instance in a ref
    useEffect(() => {
        deck = new Reveal({
            backgroundTransition: "slide",
            transition: "slide",
        });
        deck.initialize();
    }, []); // only launch useEffect at first render

    return (
        <div class="slides">
            <section>Slide 1</section>
            <section>Slide 2</section>
        </div>
    );
}
```

**Comment by bouzidanas** [comment]
For anyone who is still interested in being able to put react components inside Reveal slides, here is some solutions

# Manual

Say you have a very simple presentation:
```html
<html>
  <head>
    <link rel="stylesheet" href="dist/reveal.css">
    <link rel="stylesheet" href="dist/theme/white.css">
  </head>
  <body>
    <div class="reveal">
      <div class="slides">
        <section>Slide 1</section>
        <section>Slide 2</section>
      </div>
    </div>
    <script src="dist/reveal.js"></script>
    <script>
      Reveal.initialize();
    </script>
  </body>
</html>
```
The content of the presentation is in the `<div class="slides">` element. 

## React everywhere
If you want to create the contents entirely in React (which you can), then make this div (or preferably the parent div with `class="reveal"` https://github.com/hakimel/reveal.js/issues/2784#issuecomment-1818063790) the `#root` of your React App (using `ReactDOM.createRoot`). Dont forget to add the parts of your presentation's html to your React projects `index.html` that are needed to get the slides to work. For the example above, you would need to add:
```html
<link rel="stylesheet" href="dist/reveal.css">
<link rel="stylesheet" href="dist/theme/white.css">
```
to `index.html`'s head element and add the scripts
```html
<script src="dist/reveal.js"></script>
<script>
  Reveal.initialize();
</script>
```
somewhere at the end of `index.html`'s body element.

## React Islands
However, if you want to only sprinkle in components in specific slides, then I would make the react root element a separate element that sits outside of the reveal container div and then **use [portals](https://react.dev/reference/react-dom/createPortal) to place react component into specific sections.** 

For a simple Vite project you might end up with an `index.html` that looks like:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <link rel="stylesheet" href="dist/reveal.css">
    <link rel="stylesheet" href="dist/theme/white.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + React + TS</title>
  </head>
  <body>
    <div class="reveal">
      <div class="slides">
        <section>Slide 1</section>
        <section>Slide 2</section>
      </div>
    </div>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
    <script src="dist/reveal.js"></script>
    <script>
      Reveal.initialize();
    </script>
  </body>
</html>
```

## Paths
There is an issue with the examples provided so far and that is the paths for the reveal links and scripts. You need to make sure they are correct and they depend on how you added Reveal to your project. I would recommend using the `npm` installation method and then making sure reveal is included in the build (so it ends up in the `dist` directory).

# Programmatic

Instead of editing/manipulating the `index.html` by hand, you can add and initialize reveal in a react app source file like `main.tsx` or `app.tsx`. You can do it globally outside of app/component functions or inside one of them. In the latter case, you have to be careful not to stack initializations. Only initialize a slide deck once. If you need to reconfigure, use the `configure` function or `destroy` the deck before initializing again.

To begin, install reveal using `npm`:

```bash
npm install reveal.js
```
and to get types for typescript
```bash
npm i --save-dev @types/reveal.js
```

## imports

You will need the following imports:

```ts
import Reveal from "reveal.js";
import "reveal.js/dist/reveal.css";
import "reveal.js/dist/theme/black.css";   // "black" theme
```

Finally, just execute the code provided in the [initialization section of the Reveal.js docs](https://revealjs.com/initialization/). Make sure to use what is relevant to your case.

@t-fritsch provides a good example just above https://github.com/hakimel/reveal.js/issues/2784#issuecomment-1818433506

## Initialization issue
To contribute something to this issue thread that hasnt already been said, I will tackle the re-initialization issue in more detail.

I highly recommend using a ref to the `div` that has the `reveal` class. But even when you do, if react is in `StrictMode`, you will still get the re-initialization problem. 

Its very weird issue where the reveal deck is initialized but no flag (like `isReady`) indicated it has except the changes made by Reveal to the DOM. The latter is what I check to make sure it hasnt been previously initialized. The alternative is to remove StrictMode but I like that less.

So starting from @t-fritsch's example, I would make the following changes:

```ts
function App() {
    const deckDivRef = useRef<HTMLDivElement>(null)
    const deckRef = useRef<Reveal.Api>(null); // keep deck instance in a ref

    useEffect(() => {
        const isInitializing = deckDivRef.current?.classList.contains("reveal");
        if (isInitializing) return; // escape useEffect if deckDiv already has "reveal" classes added
        deckDivRef.current.current!.classList.add("reveal"); // add "reveal" class
        deckRef.current = new Reveal(deckDivRef.current!, {
            backgroundTransition: "slide",
            transition: "slide",
        });
        deckRef.current.initialize().then(() => {
            // good place for event handlers and plugin setups
        };

        return () => {
            // code to run on component unmount goes here
            if (!deckRef.current) return;
            try {
                deckRef.current!.destroy();
            } catch (e) {
                console.warn("destroy call failed.");
            }
        };
    }, []); // only launch useEffect at first render

    return (
        <div ref={deckDivRef }>
            <div className="slides">
                <section>Slide 1</section>
                <section>Slide 2</section>
            </div>
        </div>
    );
}
```
Note that I use the reference to the `div` element in creating the `Reveal` constructor and this is important if you want to add multiple decks to the `App`.

# react-reveal-slides
I have created a package called [react-reveal-slides](https://github.com/bouzidanas?tab=repositories) for creating reveal presentations entirely in react. It takes care of pretty much everything in the last section for you and allows you to easily create presentations using react components including all of the contents of the presentation. You can make every slide completely dynamic, control the presentation state and more. You can also create multiple presentations. 

The package is still in dev phase (although everything I just mentioned is working) and has not yet been published to `npm`. This means you will have to install it using the repo.
