### ISSUE TITLE
GitHub pages with reveal.js as dependency

### ISSUE THREAD

**Issue by smarianimore** [hakimel/reveal.js#2792]
Dear all,
I am using reveal as a dependency, as per instructions [here](https://revealjs.com/installation/#installing-from-npm), and trying to serve the presentation with GitHub pages, in [this public repo](https://github.com/smarianimore/phdXXXVI-asb).
As you can see from the GitHub page, [here](https://smarianimore.github.io/phdXXXVI-asb/), it seems reveal is not there at all.
I guessed it was due to a missing "npm install", hence tried to set up [this workflow](https://github.com/smarianimore/phdXXXVI-asb/actions/runs/281958632/workflow), that, however successful, does not resolve anything.

Have you got any clue about what am I doing wrong?
Thanks in advance.

**Comment by BryceStevenWilley** [comment]
A bit late, but I see that the site is still up and has the same problem.

From looking at https://github.com/smarianimore/phdXXXVI-asb/deployments/activity_log?environment=github-pages, it looks like Github is setup to try to serve your `master` branch to github pages. Which explains why there is no CSS styles on the page: because there are no CSS styles in the master branch. If you go to your settings for the repo, and click the pages entry in the side bar, you should be able to change Github pages to serve from your `gh-pages` branch.

I don't use reveal with npm often though, so you might need to in your workflow, but I don't think you need to run any `npm install` or `npm start` commands when using github pages. I have a few presentations ([here is one](https://github.com/BryceStevenWilley/docacon-slides)) that work on github pages without any workflow or deployment steps. I think it works fine because I commit the `dist/*css` files directly, and don't rely on the css files in the `node_modules/*` folder.

**Comment by smarianimore** [comment]
Dear @BryceStevenWilley , many thanks for your kind reply.
I setup GH page settings to serve the gh-pages branch but nothing changed.
Any other idea?

**Comment by BryceStevenWilley** [comment]
Thanks for being patient with my wrong advice, haha. Like I mentioned, I haven't worked too much with reveal with npm. 

I mistakenly thought that gh-pages would publish everything in the node_modules folder, but [that doesn't seem to be the case](https://github.com/smarianimore/phdXXXVI-asb/runs/6189628876?check_suite_focus=true#step:5:5).  [This stackoverflow answer](https://stackoverflow.com/a/43487798/11416267) says that the solution is to add an empty `.nojekyll` file in the root of the project (`touch .nojekyll`). I'd try that in the master branch, it should copy over to your gh-pages branch, if I'm understanding your workflow correctly.

**Comment by smarianimore** [comment]
Thanks again for your assistance, but unless I'm missing something (should I `touch .nojekyll` from within the workflow?), it doesn't work :(

**Comment by BryceStevenWilley** [comment]
So I checked again and it does look like github is serving everything in your `node_modules` folder correctly (you can see [reveal.css on your site](https://smarianimore.github.io/phdXXXVI-asb/node_modules/reveal.js/dist/reveal.css) now!) 

I think the issue (which is also wrong in the documentation you linked) is that the links to the CSS and JS files in `index.html` all start with a `/`, which points to the root of your site  However, your slides are being served from a sub path (/phdXXXVI-asb/), so it doesn't find those files at the root of your site. I think removing those leading `/` from:
* the CSS links 
* the JS scripts
* the `dependencies` in the `Reveal.initialize` inline script

**Comment by smarianimore** [comment]
Many thanks, it works now!
