### ISSUE TITLE
Print-pdf changes code font back to Courier

### ISSUE THREAD

**Issue by dhinojosa** [hakimel/reveal.js#2867]
When performing a print-pdf of my slides, slides with any code snippet where I have a custom CSS with Source Code Pro, the Source Code Pro gets overridden with Courier.  It's minor but would like to maintain the same aesthetic in both slides and pdf. Thanks

Reveal.js in the browser
<img width="1110" alt="Screen Shot 2020-12-17 at 8 41 51 AM" src="https://user-images.githubusercontent.com/410757/102509382-b8106200-4043-11eb-9389-313e10f00b43.png">

Reveal.js with print-pdf
<img width="1020" alt="Screen Shot 2020-12-17 at 8 42 30 AM" src="https://user-images.githubusercontent.com/410757/102509458-ceb6b900-4043-11eb-8f73-eefeaf94c997.png">

**Comment by t-fritsch** [comment]
Hi, just noticed the same issue.

it is because of the `font-family: ... !important` rule in `pdf.scss` : https://github.com/hakimel/reveal.js/blob/ccbaffc975a36f54bbcbc21211c49f2bba82751b/css/print/pdf.scss#L37-L40

I know it's a little late for a fix but as a workaround (in case anyone needs this) you can override the styles in your own css or directly in `index.html` like this : 
```html
<style>
html.print-pdf .reveal pre code {
    font-family: var(--r-code-font) !important;
}
</style>
```

@hakimel is there any reason for forcing the font for code blocks in print version ? if not I can PR ;)

**Comment by hakimel** [comment]
@t-fritsch Not sure why that was originally overridden but feel free to change it :)
