### ISSUE TITLE
chinese garbled in markdown

### ISSUE THREAD

**Issue by zhoufanglu** [hakimel/reveal.js#2872]
chinese garbled in markdown plugin

**Comment by zhoufanglu** [comment]
how to fix?

**Comment by nbatien1984** [comment]
nbatien1984@gmail.com

**Comment by akankshyasamal** [comment]
https://programmersought.com/article/24812168382/

**Comment by nbatien1984** [comment]
-- 
Tien Mega

**Comment by EloEntropy** [comment]
@zhoufanglu 
I had the same issue, but it was caused by the default encoding from the text editor I was using to write the html file. After manually saving the encoding for the html file as UTF-8, the Chinese characters were correctly displayed. I don't know if this is the same issue you are having, but it was the cause for me.

**Comment by zhoufanglu** [comment]
> @zhoufanglu
> I had the same issue, but it was caused by the default encoding from the text editor I was using to write the html file. After manually saving the encoding for the html file as UTF-8, the Chinese characters were correctly displayed. I don't know if this is the same issue you are having, but it was the cause for me.

i try it, I set UTF-8 or Chinese gibber in IDEA.
