### ISSUE TITLE
Wiki has been vandalized

### ISSUE THREAD

**Issue by fingolfin** [hakimel/reveal.js#3017]
I tried to follow the nav bar entry "Third Party Plugins " on < https://revealjs.com> which points to https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware -- but that page does not exist.

I then looked around a bit in the Wiki at https://github.com/hakimel/reveal.js/wiki and it seems to have been vandalized: pages deleted, nonsense pages / page content added.

Luckily, the wiki itself is a git repository, so it should be possible to revert it to an older version. I would recommend to restrict access to the Wiki afterwards.

**Comment by hakimel** [comment]
Thanks for letting me know—I've restored the lost pages and removed some outdated content while I was at it. 

I'm going to keep editing open for now so that people can still add their own presentations to the list of examples. If this happens again, I might close down the wiki and move that content to revealjs.com instead.
