### ISSUE TITLE
Fade transition shouldn't ease

### ISSUE THREAD

**Issue by dabrahams** [hakimel/reveal.js#3059]
I think the fade transition uses the "ease" curve, which causes a disconcerting pulse in material that is common between the two slides.  IMO fade should be linear, or there should be some sort of inverse easing for the next slide.  Until that happens, I'd really appreciate knowing how to change it in my slide deck.

Thanks!

https://user-images.githubusercontent.com/44065/141664704-c68fa099-edca-4601-91b4-e25bd54d9c28.mov

**Comment by hakimel** [comment]
If you want to switch to linear easing you can override it for all slides like this:
```css
.reveal section {
  transition-timing-function: linear !important;
}
```

I don't want to switch to linear as the default because it keeps the previous slide visible for too long which makes the transition look worse.

If much of the content is matching between two slides, you may want to consider trying auto-animate instead to avoid the pulse. You can give it a try by adding the `data-auto-animate` attribute to both slides.

**Comment by dabrahams** [comment]
Does it make the transition look worse even if it is a fade?  I was only suggesting making fades linear by default.  Can you show an example of this "worse" result?

Thanks.

**Comment by hakimel** [comment]
I was only testing linear easing for the fade transition. It looks worse
IMO because the previous slide remains visible for longer so there is a
longer period of overlap. If you switch to linear easing with a fade
transition in the default reveal.js demo you can see what I mean.  This is
all completely subjective so it’s okay if we disagree.

**Comment by dabrahams** [comment]
It's definitely OK if we disagree. I asked for an example because I consider Apple Keynote to be the benchmark, and its fade doesn't pulse.  I'd like to see the specific thing you think looks worse, and compare it with what Keynote does.  Maybe they've figured out some trick to avoid the problem you're seeing.  I notice that fade transitions in Keynote don't offer an easing selection, but maybe what they do is nonlinear nonetheless, and maybe that can be recreated in reveal. For example, if you could do easing on the “from” slide and [use a cubic bezier](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function) to create an inverted easing curve on the “to” slide, you'd probably avoid the pulse and still get the dynamics you're looking for.

**Comment by dabrahams** [comment]
@hakimel Interestingly, I still see pulsing even with the CSS change you suggested, in both Safari and Chrome.  So maybe the title of the issue is wrong, and the pulsing is a more general problem.

**Comment by hakimel** [comment]
I was curious so created a minimal example where this can be tested outside of reveal.js. Regardless of what easing I try, it seems like there is always a pulse. If anyone know how to cross fade two elements without any pulse/flash I'd love to revise the fade in reveal.js.

https://codepen.io/hakimel/pen/cc70f90c32ea6ce287a543a33fd9809f?editors=1100

**Comment by dabrahams** [comment]
This is interesting; [opacity doesn't compose](https://codepen.io/dabrahams/pen/YzxBBGg)… and on reflection it's almost obvious why (though I don't know how to explain it in words). I do wonder how to make a proper fade transition in that case.  Maybe some of my Adobe colleagues can help.

**Comment by dabrahams** [comment]
Oh wait, this is easy.  http://css3.bradshawenterprises.com/cfimg/ gave me the answer: simply transition the new slide's opacity from 0 to 1 in front of the old slide.  Once the transition is over, you can hide the old slide if that helps (e.g. for performance or something).

**Comment by hakimel** [comment]
Thanks for looking into it. I don't like how it looks when the content overlaps for that long so unfortunately I don't want to use that for the default fade transition.

Here's a screen recording showing how it would look. The first tab fully fades in the new slide before fading out the old one. The second tab is the existing fade transition.

https://user-images.githubusercontent.com/629429/142590999-b123c6c4-ac04-4c11-be5e-aeedc937a7ff.mp4

**Comment by dabrahams** [comment]
I see what you mean, but I strongly suspect the problem in this case is that the background of the new slide doesn't fully overlap the foreground of the old slide.  IIRC the backgrounds are in a separate stack from the foregrounds?  To make this look right, you need to fade a completely opaque slide region in on top of whatever is going to be obscured.  Hiding the old slide is then completely optional.  If things don't look right until you've hidden the old slide, you haven't implemented the technique I'm describing.

**Comment by dabrahams** [comment]
(Maybe as a quick hack to see how that changes things you could add a style attribute on everything that sets z-order)

**Comment by Voll3r** [comment]
Apologies for digging out this old issue, but I just stumbled across the same problem as dabrahams and my first instinct was also to switch to linear fade. When I saw that it doesn't give the desired result, I wanted to better understand why.

If the issue is fixable, I think it could greatly improve the aesthetics. I often use similar titles from slide to slide, e.g. "Slide Transitions - Overall Concept" -> "Slide Transitions - Available Options". The flicker in the transition is unfortunately rather disturbing.

Here's my understanding of why the flicker occurs in the first place:

My understanding is that background and content transition separately. If the background remains the same, and the content is rendered on top of it, only the content transitions.

Say we have a pitch black background (#000000) with white font (#FFFFFF) on both slides. During the transition, the opacity of the outgoing content goes from 100% -> 0% and vice versa with the incoming content.

I believe this is **first** calculated as the result of the semi-transparent outgoing content on top of the background, with the semi-transparent incoming content put on top of the **result** of the first calculation.

Say we're at 50% / 50% opacity during the transition.

White at 50% opacity on top of black -> 50% grey (#808080)
White at 50% opacity op top of 50% grey -> 75% grey (#BFBFBF)

Even though we'd expect a white font all the way through the transition, the colour gets much darker and we see this as a flicker. If we have an image on top of a white background (like in dabrahams' example), the flicker will be towards the bright end.

Mathematically there should be two possible solutions:

1. Blending is done on the content **only** first (incoming and outgoing), and the result is then superimposed onto the background.
2. Transition is done on the full slides (content **and** background). The complete slide fades out while the next slide fades in.

Whatever function is used for the opacity, it needs to be symmetrical, i.e. at any point in the transition both opacities must add up to 1.

As you can probably tell, I'm not an HTML/CSS/JS guy, so my apologies if I don't have a grasp on what the machine does in the background.
