### ISSUE TITLE
mark slide as hidden

### ISSUE THREAD

**Issue by buaziz** [hakimel/reveal.js#315]
i have a presentation on a TV monitor that gets updates, and i have 2 questions 
1. how can i mark a slide as hidden from the presentation - preferably with data attributes as i am using knockout (knockout visible property just changes the style attr. which is not picked up )
2. if the slides change visibility do i need to reinitialize reveal every time ? or is their a better way.

**Comment by schlichtanders** [comment]
I stumbled upon this and #1301 because I also would like to hide slides easily

could you provide an example of how to attach/reattach the slides?

**Comment by jeroenheijmans** [comment]
FWIW: I've asked [a similar question on Stack Overflow](https://stackoverflow.com/q/58578485/419956). My use case is to _skip_ a "backup" slide by default, and only show it if the presenter explicitly chooses to do so.

As a workaround, I can of course just quickly click through the backup slide.

If it turns out I need to write something myself for this I'll try to remember sharing it here as a gist, as a plugin, or on the Stack Overflow thread.

**Comment by tomron** [comment]
@jeroenheijmans  did you happen to write that gist eventually? TIA!

**Comment by jeroenheijmans** [comment]
@tomron Nope! I went low-tech, and did _nothing_ to fix this 😅. 

[My specific use case](https://github.com/jeroenheijmans/presentation-learning-at-lightning-speed/blob/1004ad02d1307a0da61eb7fef2e869d35d49a7cb/index.html#L176-L195) had a slide say "DEMO TIME!" which made me switch to my IDE, and then a "TEH CODEZ" backup slide, which I actually briefly _showed_ and mentioned it was there for if people wanted to check the slides later.

**Comment by hakimel** [comment]
As of reveal.js 4.1 all slides with `data-visibility="hidden"` are hidden from view.

Not sure when 4.1 will be released but the change is available in the dev branch, see d272628f5824135a4a571e6c49f5f18e019520cf.
