### ISSUE TITLE
data-background doesn't support webp image format

### ISSUE THREAD

**Issue by greendinosaur** [hakimel/reveal.js#3200]
I've been resizing some images to use the webp format and I noticed that data-background does not support webp format. Is there a reason for this?

I took a look at the revealjs code and the code to render the background restricts the image types passed into the data-background attribute and webp isn't included in the list. I'm happy to make the code change to support webp and do a pull request, just wanted to check if there was a reason it's not supported.

https://developers.google.com/speed/webp/ has more info on this image format.

**Comment by hakimel** [comment]
I've made the `data-background` image detection work for webp now too. Turns out this only affected webp images loaded locally via `data-background`.

These already worked:
`<section data-background="https://www.gstatic.com/webp/gallery/1.webp"></section>`
`<section data-background-image="1.webp"></section>`

This did not work before:
`<section data-background="1.webp"></section>`

**Comment by greendinosaur** [comment]
Great, thanks for fixing.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
