### ISSUE TITLE
Pug templates support

### ISSUE THREAD

**Issue by unrealsolver** [hakimel/reveal.js#3274]
As an experienced web developer and revealjs user, I want to have:
- clearer and less verbose syntax
- ability to extend/include presentation pieces
- simple loops/conditions and custom tags

All of these is achievable with `pug` templates. See https://pugjs.org

**Comment by Martinomagnifico** [comment]
It is probably out of the scope of Reveal.js. This PR only works through Gulp in the "Full Setup" installation. It won't work in the "Basic setup" or NPM installation. So the PR is more of a change in the build setup than a change in Reveal.js itself. 

Any developer can adjust the gulpfile to add Pug support (I do it as well, I prefer writing Pug compared to HTML, the same as I prefer writing SCSS to CSS), but that still does not change Reveal itself. So the proposed text change _"The framework comes with […] Pug templates support […]"_ would not be accurate.

**Comment by unrealsolver** [comment]
@Martinomagnifico, make sense. I removed changes in README. Though, I agree that any developer *can* adjust gulpfile, but I am not sure that any developer *would* adjust it, so I think this small change still make sense.

**Comment by Martinomagnifico** [comment]
Hi @unrealsolver, 
It's up to anyone to choose their Gulp setup, and developers who want to choose a certain engine or any flow improvement, will know how to do that. If you want Reveal to add it, then the same logic would then go for every template language out there. I appreciate the effort, but I don't think @hakimel will do that.
I guess if you have a nice setup for presentations that works well, you can add it as a reveal-pug-starter project on Github, so that people can start from that as well.

**Comment by Martinomagnifico** [comment]
Hi @unrealsolver, I made a project here: [Reveal-pug-scss-starter](https://github.com/Martinomagnifico/reveal-pug-scss-starter). Feel free to fork it, add stuff to it, PR changes etcetera.

**Comment by Martinomagnifico** [comment]
@unrealsolver can we close this issue? It's really something out of the scope of Reveal.js.
