### ISSUE TITLE
Remove page number from a single slide (mid presentation)

### ISSUE THREAD

**Issue by TorkelE** [hakimel/reveal.js#3393]
I would like to remove page numbers from a single slide in my presentation (which I want to be fully blank). Is there a way to do this?

**Comment by Martinomagnifico** [comment]
To control things outside the slides, per slide, you can use `data-state`. 

```
<div class="slides">
    <section>Slide 1</section>
    <section data-state="blankslide">Slide 2</section>
    <section>Slide 3</section>
</div>
```

This adds the class that you give it to the viewport element of the presentation. Then you can use CSS to control things like opacity (which you can use to give it a nice transition if you like).

```
.blankslide .reveal .controls,
.blankslide .reveal .slide-number,
.blankslide .reveal .progress {
    opacity: 0;
}
```

You can also add `data-visibility="uncounted"` to the slide, so that the slide is also not counted, like this:

```
<div class="slides">
    <section>Slide 1</section>
    <section data-state="blankslide" data-visibility="uncounted">Slide 2</section>
    <section>Slide 3</section>
</div>
```

**Comment by Martinomagnifico** [comment]
To add a smooth transition, use CSS like this:

```
.reveal .controls,
.reveal .slide-number,
.reveal .progress {
    transition: opacity 0.2s ease-in-out;
}
```
