### ISSUE TITLE
custom slide links instead of hash

### ISSUE THREAD

**Issue by arfizato** [hakimel/reveal.js#3430]
is there a plugin or a way to use custom urls like "/intro" or "/about" instead of the usual hash? 
if not, is there a way modify the behavior by writing a plugin to override the hashes with provided strings or default to the first H1 in the slide? 

I have just discovered reveal.js i spent a couple hours looking in the plugins page and looking through documentations and the closest thing i found is [simplemenu](https://martinomagnifico.github.io/reveal.js-simplemenu/demo-manual-id.html) plugin. but even the plugin reverts to displaying the hash after the page loads.

This is btw an amazing library. i plan to use it for my portfolio and for future presentations.

**Comment by libralibra** [comment]
i am sure the current version supports the section id and link. But you need at least one # to do that.

``	<a href="#/grand-finale">Go to the last slide</a>
...
section id="grand-finale"

**Comment by t-fritsch** [comment]
@libralibra is right, when you give an `id="..."` attribute on a section, the hash in the URL uses that id instead of the slide number :

```html
<section id="grand-finale">Slide1 content</section>
```
When navigating to this slide, you will see in the browser's adress bar the hash `/#/grand-finale` instead of `/#/1` (_or any number depending on the slide's order_).

If you use markdown files, you can use the `<!-- .slide: -->` comment (https://revealjs.com/markdown/#slide-attributes) like this :

```md
<!-- .slide: id="grand-finale" -->
Slide 1 content

---
<!-- .slide: id="bonus" -->
Slide 2 content
``` 

This is documented in the jump-to-slide documentation : https://revealjs.com/jump-to-slide/#navigating-to-slide-number
