### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [hakimel/reveal.js#3469]
Describe the bug
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

Steps To Reproduce
In Landing page header section see twitter old logo

Expected behavior
Twitter logo should be changed to X

Screenshot
<img width="960" alt="Screenshot 2023-09-10 080401" src="https://github.com/hakimel/reveal.js/assets/91591901/2050bf9b-c9f2-4e69-822a-647e6226d519">

@hakimel
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by skyboyer** [comment]
just fyi official website lives in a separate repo: https://github.com/reveal/revealjs.com

**Comment by pragyamishra56** [comment]
@skyboyer could you assign with me it would be my 1st contribution

**Comment by t-fritsch** [comment]
I'm closing this issue since as @skyboyer said, this repo is dedicated to reveal js code, not its website. This issue could be posted in https://github.com/reveal/revealjs.com/issues, and you can also [fork the website repo](https://github.com/reveal/revealjs.com/fork), commit your changes in your fork and then submit a pull request (also as @skyboyer said).
