### ISSUE TITLE
slidechange fires twice

### ISSUE THREAD

**Issue by effeksys** [hakimel/reveal.js#54]
"slidechanged" event fires twice!? 

index.html - line 288
// Fires each time a new slide is activated
Reveal.addEventListener( 'slidechanged', function( event ) {
    // event.indexh & event.indexv
} );

**Comment by vijayabal** [comment]
Hi, This issue is still I am getting. Called slide change twice - this.reveal.addEventListener('slidechanged', this.slidePageChange.bind(this)); Also, Reveal Js is not working initial rendering in SPA application like angular. To resolve, we need to reinitialise it again in each components.

// Reinitialize the reveal
  reinitialize() {
    this.reveal.initialized = false;
  }
