### ISSUE TITLE
Stretch to full browser width

### ISSUE THREAD

**Issue by rparree** [hakimel/reveal.js#565]
Hi, 

I am using a lot of BNF railroad diagrams in my current presentation. I need to every now and then stretch beyond the "section frame" and use some of the space. 
I am not (yet) sure why the code below does not work

``` javascript
toArray( dom.slides.querySelectorAll( 'section > .full-width' ) ).forEach( function( element ) {
    $(element).width( $(window).width());
    $(element).offset({left:0});
} );
```

But when the browser height is not maximized, the full width is not used and a big portion on the right is left unused.

Does this perhaps have to do with some scaling or other dynamic behavior of the slide rendering?

**Comment by abubelinha** [comment]
@hakimel I tried what you said (100% width & height) in order to let slides enter as much text as possible.

And that did work great on my desktop presentation. 
But the mobile vision gets incredibly disturbed, with huge fonts which completely overflow the screen (Android Samsung galaxy S3 default browser)

Any chances to make this solution also mobile compatible?
Thanks
