### ISSUE TITLE
Load reveal.js as a library instead of a forked repository

### ISSUE THREAD

**Issue by joelmccracken** [hakimel/reveal.js#718]
I would really love to load reveal as a library instead of forking/downloading the repository. How do you feel about that?

**Comment by marcvangend** [comment]
It's been more than 4 years since this issue was created and closed. I love Reveal, used it many times, but this question keeps popping up in my mind every time I set up a new slide deck: Could Reveal be more of a library, less of a template?

@hakimel I understand and respect the answer you gave before closing this issue, but I'm curious if your opinion has changed over time, and if you think that new technologies have made the library-approach a more feasible option.
